# .github/workflows/deploy.yml

name: Node CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # yarn.lock을 hash로 하는 node_modules cache 생성
      - name: Cache Yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Yarn Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vuepress/dist
          
      - name: Update Algolia Search Engine
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: '{
            "index_name": "giwon",
            "start_urls": ["https://giwonn.github.io/"],
            "stop_urls": [],
            "selectors": {
              "lvl0": {
                "selector": ".sidebar-heading.active",
                "global": true,
                "default_value": "Documentation"
              },
              "lvl1": ".theme-default-content h1",
              "lvl2": ".theme-default-content h2",
              "lvl3": ".theme-default-content h3",
              "lvl4": ".theme-default-content h4",
              "lvl5": ".theme-default-content h5",
              "text": ".theme-default-content p, .theme-default-content li",
              "lang": {
                "selector": "/html/@lang",
                "type": "xpath",
                "global": true
              }
            },
            "custom_settings": {
              "attributesForFaceting": ["lang"]
            }
          }'
